---
- hosts: localhost
  tasks:
  - name: create folder temp
    file:
      path: /root/temp
      state: directory
      mode: 0777

  - name: Download foo.conf
    become: yes
    get_url:
      url: https://www.7-zip.org/a/7z2200-x64.exe
      dest: /root/temp
      mode: 0777
      force_basic_auth: yes

