---
 
- hosts: all
  gather_facts: false

  tasks:
    - name: check the service status
      win_service:
        name: "{{ service_name }}"
      register: service_status

    - block:
    
        - name: display the service current status
          debug:
            msg: 
              - "Service name: {{ service_status.name }}"
              - "Service start mode: {{ service_status.start_mode }}"
              - "Service state: {{ service_status.state }}"    
          
        - name: Service restart / stop / disabld operations
          win_service:
            name: "{{ service_name }}"
            state: "{{ service_state }}"
            start_mode: "{{ service_start_mode |default('automatic') }}"

        - name: get the service status post operations
          win_service:
            name: "{{ service_name }}"
          register: service_status_post
        
        - name: display the status
          debug:
            msg: 
              - "Service name: {{ service_status_post.name }}"
              - "Service start mode: {{ service_status_post.start_mode }}"
              - "Service state: {{ service_status_post.state }}"             
      when: service_status.exists == true
