---
- hosts: win
  tasks:
  - name: Get disk facts
    win_disk_facts:
 
  - name: output first disk size
    debug:
      var: ansible_facts.disk[0].size

  - name: convert first system disk in to various formats
    debug:
      msg: '{{ disksize_gb }} vs {{ disksize_gib_human }}'
    vars:
      # get first system disk
      disk: '{{ ansible_facts_disks |selectattr("system_disk")|first }}'
      # Show disk size in Gibibytes
      disksize_gib_human: '{{ disk.size|filesizeformat(true) }}'
      disksize_gib: '{{ (disk.size/1024|pow(3))|round|int }} GiB'

#```yaml
#---
- hosts: win
  tasks:
  - name: Get disk facts
    win_command:
      wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed, status
    register: usage

  - debug:
      msg: "{{ usage.stdout }}"


