################################################################################
# ANSIBLE PLAYBOOK FOR DEUTSCHE BANK - PRECHECKS                               #
#                                                                              #
# DEVELOPED BY : DXC CLOUD AUTOMATION TEAM                                     #
#                                                                              #
# VERSION: 1.0                                                                 #
#                                                                              #
# PURPOSE OF THIS PLAYBOOK:                                                    #
# Playbook to check whether given packages are available in the system         #
################################################################################
# VERSION HISTORY:                                                             #
#  1.0 (INITIAL VERSION)                                                       #
################################################################################
---
  - name: "linux->pkg | Check if given package is available in the package_facts"
    block:
      ################################################################################
      # Update HTML if the package is available in the system                        #
      ################################################################################
      - name: "linux->pkg | Update HTML line - if given package is available in the system"
        set_fact:
          html_email_lines: "{{ html_email_lines }} + [ '<tr><td align=\"center\"> Package {{ item }} </td><td align=\"center\"><font color=\"green\"><b> OK </b></font></td><td> Package {{ item }} is available in the system </td></tr>' ]"
        when: ansible_facts.packages[item][0]['name'] == item

    rescue:
      ################################################################################
      # Update HTML with status as "NOT-OK" if any step mentioned above failed       #
      ################################################################################
      - name: "linux->pkg | Update HTML line - if given package is NOT available in the system"
        set_fact:
          html_email_lines: "{{ html_email_lines }} + [ '<tr><td align=\"center\"> Package {{ item }} </td><td align=\"center\"><font color=\"red\"><b> NOT-OK </b></font></td><td> Package {{ item }} is NOT available in the system </td></tr>' ]"
